const piket = [
  {
    id: "1",
    nama: "Abrar Wahid",
    sesi: "1",
    hari: "Senin",
    waktu: "09:00-12:00",
  },
  {
    id: "2",
    nama: "Ahmad Nur Ain",
    sesi: "1",
    hari: "Senin",
    waktu: "09:00-12:00",
  },
  {
    id: "3",
    nama: "Ai Nurlaeli Maulatul Azizah",
    sesi: "1",
    hari: "Senin",
    waktu: "09:00-12:00",
  },
  {
    id: "4",
    nama: "Anis Agustin",
    sesi: "2",
    hari: "Senin",
    waktu: "12:00-15:00",
  },
  {
    id: "5",
    nama: "Desfi Silvia Aros",
    sesi: "2",
    hari: "Senin",
    waktu: "12:00-15:00",
  },
  {
    id: "6",
    nama: "Dhea Anggi Natasya",
    sesi: "2",
    hari: "Senin",
    waktu: "12:00-15:00",
  },
  {
    id: "7",
    nama: "Dwi Ferdiansyah",
    sesi: "1",
    hari: "Selasa",
    waktu: "09:00-12:00",
  },
  {
    id: "8",
    nama: "Ervan Satrya Perdana",
    sesi: "1",
    hari: "Selasa",
    waktu: "09:00-12:00",
  },
  {
    id: "9",
    nama: "Farhan Basyari",
    sesi: "1",
    hari: "Selasa",
    waktu: "09:00-12:00",
  },
  {
    id: "10",
    nama: "Gugun Guntara",
    sesi: "2",
    hari: "Selasa",
    waktu: "12:00-15:00",
  },
  {
    id: "11",
    nama: "Milhatun Nida",
    sesi: "2",
    hari: "Selasa",
    waktu: "12:00-15:00",
  },
  {
    id: "12",
    nama: "Putri Nabila Kosasih",
    sesi: "2",
    hari: "Selasa",
    waktu: "12:00-15:00",
  },
  {
    id: "13",
    nama: "Retno Sari Sirotujanah",
    sesi: "1",
    hari: "Rabu",
    waktu: "09:00-12:00",
  },
  {
    id: "14",
    nama: "Reyhan Vemas Perdiansyah",
    sesi: "1",
    hari: "Rabu",
    waktu: "09:00-12:00",
  },
  {
    id: "15",
    nama: "Riri Nurazizah",
    sesi: "1",
    hari: "Rabu",
    waktu: "09:00-12:00",
  },
  {
    id: "16",
    nama: "Sandi Firdaus",
    sesi: "2",
    hari: "Rabu",
    waktu: "12:00-15:00",
  },
  {
    id: "17",
    nama: "Satria Winata",
    sesi: "2",
    hari: "Rabu",
    waktu: "12:00-15:00",
  },
  {
    id: "18",
    nama: "Shalma Primasari Dewi",
    sesi: "1",
    hari: "Kamis",
    waktu: "09:00-12:00",
  },
  {
    id: "19",
    nama: "Surya Sakti Sujana",
    sesi: "1",
    hari: "Kamis",
    waktu: "09:00-12:00",
  },
  {
    id: "20",
    nama: "Valmadia Alviana Gunawan",
    sesi: "1",
    hari: "Kamis",
    waktu: "09:00-12:00",
  },
  {
    id: "21",
    nama: "Vikri Akbar",
    sesi: "2",
    hari: "Kamis",
    waktu: "12:00-15:00",
  },
  {
    id: "22",
    nama: "Zacky Hafsari",
    sesi: "2",
    hari: "Kamis",
    waktu: "12:00-15:00",
  },
];

module.exports = piket;
